export const ADDTOCART='ADDDTOCART'
export const SAVEITEM='SAVEITEM'
export const PROCESSPAYMENT='PROCESSPAYMENT'
export const INCREASE_QUANTITY='INCREASE_QUANTITY'
export const DECREASE_QUANTITY="DECREASE_QUANTITY"
export const DELETE_Quantity="DELETE_Quantity"
